import localFont from "next/font/local";
import "./globals.css";
import Headers from "../components/header";
import Footer from "../components/footer";
import Banner from "../components/banner"; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "THINKLife® SuperBeena",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Banner />
        <Headers />
        {children}
        <Footer />
      </body>
    </html>
  );
}
